# Generated by Django 5.2 on 2025-04-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_booking_options_booking_event_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='equipment',
        ),
        migrations.AddField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(blank=True, to='booking.equipment'),
        ),
    ]
